### PR TITLE
New json data type (pg 12)

### PR DESCRIPTION
**Pull request by rapomon**
https://www.postgresql.org/docs/12/datatype-json.html#DATATYPE-JSONPATH

### CODE REVIEW

**Comment by ozum** [comment]
Thanks. I published to npm.

**Comment by rapomon** [comment]
Thanks to you. I just updated the version, but I don't see the change in /node_modules/pg-structure/dist/util/built-in-types.js?

**Comment by ozum** [comment]
I fixed. Please update again.

**Comment by rapomon** [comment]
Yes, now it works, thank you!

**Pull request merged**
